<section class="*">

    <div class="xv-slider-wrap text-white" >
        <div class="lSSlideOuter "><div class="lSSlideWrapper usingCss" style="transition-duration: 400ms; transition-timing-function: ease;"><div class="lightSlider showSlider lSSlide lsGrab" data-item="1" data-pager="false" data-slide-margin="0" data-gallery="false" data-pause="8000" data-pauseonhover="true" data-auto="true" data-loop="true" style="width: 6745px; transform: translate3d(-4047px, 0px, 0px); height: 640px; padding-bottom: 0%;"><div class="xv-slide clone left" style="width: 1349px; margin-right: 0px;">
                        <div class="container">
                            <div class="row">
                                <div class="col-12 col-lg-6 fadeInRight animated">
                                    <div class="xv-slider-content clearfix color-white">
                                        <h1>Paper Pages</h1>
                                        <p>When we designed MacBook Pro with Retina display, we started with a blank
                                            slate. That gave us the freedom</p>
                                        <div class="p-t-40"><a href="#" class="btn btn-primary btn-lg">Buy Now 19$</a>
                                            <a href="#" class="btn btn-success btn-lg">View All Demos</a>
                                        </div>
                                    </div>
                                </div>
                                <div class="hidden-sm-down col-lg-6 fadeInLeft animated">
                                    <img src="assets/lppm/img/demo/slider/desktop.png" alt="">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="xv-slide lslide" style="width: 1349px; margin-right: 0px;">
                        <div class="container">
                            <div class="row">
                                <div class="col-12 col-lg-6 fadeInRight animated go">
                                    <div class="xv-slider-content clearfix color-white ">
                                        <h1>Paper Social App</h1>
                                        <p>Sed eget orci eleifend enim mattis suscipit. Suspendisse potenti non ipsum.</p>
                                        <div class="p-t-40"><a href="#" class="btn btn-img">
                                                <img src="assets/lppm/img/basic/btn-appstore.png" alt=""> </a>
                                            <a href="#" class="btn btn-img">
                                                <img src="assets/lppm/img/basic/btn-googleplay.png" alt="">
                                            </a>
                                        </div>
                                    </div>
                                </div>
                                <div class="hidden-sm-down col-lg-6 fadeInLeft animated go">
                                    <img src="assets/lppm/img/demo/slider/iphone.png" alt="">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="xv-slide lslide" style="width: 1349px; margin-right: 0px;">
                        <div class="container">
                            <div class="row">
                                <div class="hidden-sm-down col-lg-6 fadeInLeft animated go">
                                    <img src="assets/lppm/img/demo/slider/rocket.png" alt="">
                                </div>
                                <div class="col-12 col-lg-6 fadeInRight animated go">
                                    <div class="xv-slider-content clearfix color-white">
                                        <h1>Paper Booster</h1>
                                        <p>When we designed MacBook Pro with Retina display, we started with a blank
                                            slate. That gave us the freedom to imagine something radical, something
                                            entirely different.</p>
                                        <div class="p-t-40"><a href="#" class="btn btn-primary btn-lg">Buy Now 19$</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="xv-slide lslide active" style="width: 1349px; margin-right: 0px;">
                        <div class="container">
                            <div class="row">
                                <div class="col-12 col-lg-6 fadeInRight animated go">
                                    <div class="xv-slider-content clearfix color-white">
                                        <h1>Paper Pages</h1>
                                        <p>When we designed MacBook Pro with Retina display, we started with a blank
                                            slate. That gave us the freedom</p>
                                        <div class="p-t-40"><a href="#" class="btn btn-primary btn-lg">Buy Now 19$</a>
                                            <a href="#" class="btn btn-success btn-lg">View All Demos</a>
                                        </div>
                                    </div>
                                </div>
                                <div class="hidden-sm-down col-lg-6 fadeInLeft animated go">
                                    <img src="assets/lppm/img/demo/slider/desktop.png" alt="">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="xv-slide clone right" style="width: 1349px; margin-right: 0px;">
                        <div class="container">
                            <div class="row">
                                <div class="col-12 col-lg-6 fadeInRight animated">
                                    <div class="xv-slider-content clearfix color-white ">
                                        <h1>Paper Social App</h1>
                                        <p>Sed eget orci eleifend enim mattis suscipit. Suspendisse potenti non ipsum.</p>
                                        <div class="p-t-40"><a href="#" class="btn btn-img">
                                                <img src="assets/lppm/img/basic/btn-appstore.png" alt=""> </a>
                                            <a href="#" class="btn btn-img">
                                                <img src="assets/lppm/img/basic/btn-googleplay.png" alt="">
                                            </a>
                                        </div>
                                    </div>
                                </div>
                                <div class="hidden-sm-down col-lg-6 fadeInLeft animated">
                                    <img src="assets/lppm/img/demo/slider/iphone.png" alt="">
                                </div>
                            </div>
                        </div>
                    </div></div><div class="lSAction"><a class="lSPrev"><span class="icon-left-arrow"></span></a><a class="lSNext"><span class="icon-right-arrow"></span></a></div></div></div>
    </div>
    <!--slider Wrap-->

</section>



        <section class="p-t-80 s1 masonry-post relative">


            <div class="container">

                <header class="section-heading se">
                    <h1 class="s-64 font-weight-bolder text-left">Pelayanan

                        <small class="text-green"> lppm</small>

                    </h1>
                </header>
                <div class="row">
                    <div class="col-lg-6 mx-lg-auto">

                    </div>
                </div>
                <div class="p-t-b-40">
                    <div class="row">
                        <div class="col-md-4">
                            <div class="service-block center paper-block">
                                <div class="service-icon"><i class="icon icon-bug text-red" aria-hidden="true"></i>
                                </div>
                                <div class="service-content">
                                    <h3 class="my-3"><a href="#">Paper Service Heading</a></h3>
                                    <p>Dynamically leverage existing synergistic systems whereas future-proof
                                        sources Synergistically formulate</p>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="service-block center paper-block">
                                <div class="service-icon"><i class="icon icon-pie-chart text-purple" aria-hidden="true"></i>
                                </div>
                                <div class="service-content">
                                    <h3 class="my-3"><a href="#">Paper Service Heading</a></h3>
                                    <p>Dynamically leverage existing synergistic systems whereas future-proof
                                        sources Synergistically formulate</p>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="service-block center paper-block">
                                <div class="service-icon">
                                    <i class="icon icon-cube text-bg-success" aria-hidden="true"></i>
                                </div>
                                <div class="service-content">
                                    <h3 class="my-3"><a href="#">Paper Service Heading</a></h3>
                                    <p>Dynamically leverage existing synergistic systems whereas future-proof
                                        sources Synergistically formulate</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </section>


<div class="portfolio container">
    <div class="masonry-container">
        <section class="p-t-b-50 s2 masonry-post">
            <div class="container">
                <header class="section-heading se">
                    <h1 class="s-64 font-weight-bolder text-right">Tentang

                        <small class="text-green"> lppm</small>

                    </h1>
                </header>
                <div class="row">
                    <div class="col-xl-6 col-lg-6 col-md-6 col-12">
                        <header>
                            <h2>About Paper</h2>
                        </header>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In risus neque,
                            pretium id sollicitudin nec, bibendum at leo. Nullam condimentum, sem scelerisque
                            volutpat nec odio. Aenean erat jm suscipit, purus ligula euismod est, molestie
                            blandit quam nunc a nisl. Quisque at sapien sit amet quam pharetra molestie.</p>
                        <p>Fusce sodales accumsan tincidunt. Phasellus quis feugiat urna. Aenean
                            tempus augue feugiat vulputate sodales. Suspendisse euismod, eros ac convallis
                            placerat, am faciliuam vitae mi. Sed a ipsum porta, pretium ipsum eget,
                            dignissim mi.</p>
                    </div>
                    <div class="col-xl-6 col-lg-6 col-md-6 col-12">
                        <header>
                            <h2>Our Experience</h2>
                        </header>
                        <div class="progress-wrapper p-b-20 animatedParent">
                            <span>Web Design</span>
                            <div class="progress progress-xs">
                                <div class="progress-bar progress-dark animated slideInLeft go" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 80%;">
                                    <span class="sr-only">80% Complete</span>
                                </div>
                            </div>
                        </div>
                        <!--progress wrapper-->
                        <div class="progress-wrapper p-b-20 animatedParent">
                            <span>Web Development</span>
                            <div class="progress progress-xs">
                                <div class="progress-bar progress-dark animated slideInLeft" role="progressbar" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100" style="width: 90%;">
                                    <span class="sr-only">90% Complete</span>
                                </div>
                            </div>
                        </div>
                        <!--progress wrapper-->
                        <div class="progress-wrapper p-b-20 animatedParent">
                            <span>Frontend Development</span>
                            <div class="progress progress-xs">
                                <div class="progress-bar progress-dark animated slideInLeft" role="progressbar" aria-valuenow="85" aria-valuemin="0" aria-valuemax="100" style="width: 85%;">
                                    <span class="sr-only">85% Complete</span>
                                </div>
                            </div>
                        </div>
                        <!--progress wrapper-->
                        <div class="progress-wrapper p-b-20 animatedParent">
                            <span>Photography</span>
                            <div class="progress progress-xs">
                                <div class="progress-bar progress-dark animated slideInLeft" role="progressbar" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100" style="width: 70%;">
                                    <span class="sr-only">70% Complete</span>
                                </div>
                            </div>
                        </div>
                        <!--progress wrapper-->
                        <div class="progress-wrapper p-b-20 animatedParent">
                            <span>iOS Development</span>
                            <div class="progress progress-xs">
                                <div class="progress-bar progress-dark animated slideInLeft" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%;">
                                    <span class="sr-only">60% Complete</span>
                                </div>
                            </div>
                        </div>
                        <!--progress wrapper-->
                    </div>
                    <!--col-->
                </div>
                <!--row-->
            </div>
        </section>
        <section class="p-t-b-50 s3 masonry-post">
            <div class="container">
                <header class="section-heading se">
                    <h1 class="s-64 font-weight-bolder text-left">about

                        <small class="text-blue"> us</small>

                    </h1>
                </header>
                <div class="row">
                    <div class="col-xl-6 col-lg-6">
                        <header>
                            <h2>About Paper</h2>
                        </header>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In risus neque,
                            pretium id sollicitudin nec, bibendum at leo. Nullam condimentum, sem scelerisque
                            volutpat nec odio. Aenean erat jm suscipit, purus ligula euismod est, molestie
                            blandit quam nunc a nisl. Quisque at sapien sit amet quam pharetra molestie.</p>
                        <p>Fusce sodales accumsan tincidunt. Phasellus quis feugiat urna. Aenean
                            tempus augue feugiat vulputate sodales. Suspendisse euismod, eros ac convallis
                            placerat, am faciliuam vitae mi. Sed a ipsum porta, pretium ipsum eget,
                            dignissim mi.</p>
                    </div>
                    <div class="col-xl-6 col-lg-6 col-md-6 col-12">
                        <header>
                            <h2>Pengumuman</h2>
                        </header>

                        <div class="list-group text-green">
                            <a href="#" class="list-group-item">Cras justo odio</a>
                            <a href="#" class="list-group-item">Dapibus ac facilisis in</a>
                            <a href="#" class="list-group-item">Morbi leo risus</a>
                            <a href="#" class="list-group-item">Porta ac consectetur ac</a>
                            <a href="#" class="list-group-item">Vestibulum at eros</a>
                            <a href="#" class="list-group-item">Morbi leo
                                risus</a>
                        </div>
                    </div>
                    <!--row-->
                </div>
        </section>
        <section class="p-t-b-50 s4 masonry-post">
            <div class="container">
                <header class="section-heading">
                    <h1 class="s-64 font-weight-bolder text-right">Kontak
                        <small class="text-green"> lppm</small>
                    </h1>
                </header>
                <div class="row">
                    <div class="col-lg-8">
                        <div class="contactFormWrapper">
                            <form id="contactform" action="/assets/php/submit.php" method="post">
                                <div class="row">
                                    <div class="col-12 col-lg-6">
                                        <label for="name" class="required">Name</label>
                                        <input class="form-control form-control-lg" type="text" name="name"
                                               id="name">
                                    </div>
                                    <div class="col-12 col-lg-6">
                                        <label for="subject" class="required">Subject</label>
                                        <input class="form-control form-control-lg" type="text"
                                               name="subject" id="subject">
                                    </div>
                                    <div class="col-12">
                                        <label for="company" class="required">Company Name</label>
                                        <input class="form-control form-control-lg" type="text"
                                               name="company" id="company">
                                    </div>
                                    <div class="col-12 col-lg-6">
                                        <label for="email" class="required">Email Address</label>
                                        <input class="form-control form-control-lg" type="text"
                                               name="email" id="email">
                                    </div>
                                    <div class="col-12 col-lg-6">
                                        <label for="phone" class="required">Tel/Mob</label>
                                        <input class="form-control form-control-lg" type="text"
                                               name="phone" id="phone">
                                    </div>
                                </div>
                                <label for="message" class="required">Message</label>
                                <textarea placeholder="Message" name="message" id="message"
                                          class="form-control-lg"></textarea>
                                <div class="text-right p-t-20">
                                    <button class="btn btn-primary btn-lg"><i class="icon icon-envelope-o"></i> Send
                                        Message
                                    </button>
                                </div>
                            </form>
                            <div class="p-t-b-20">
                                <div id="valid-issue" class="alert" style="display:none;"></div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="p-t-b-20">
                            <div class="widget widget-address">
                                <h3>Location</h3>
                                <div class="p-t-b-20"><strong>Address:</strong>
                                    <p>1814 NE Miami Gardens Drive, Suite #1007, North Miami Beach, FL, 33179</p>
                                    <strong> Email : </strong>
                                    <p>info@avalon.com</p> <strong>Phone: </strong>
                                    <p>00.987.1234 - 800.123.3210</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div></div>